name: analysis-engine PR checker

on: 
  pull_request:
    branches: [ main ]

jobs:
  pull_request_test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./packages/analysis-engine
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: download codes
      uses: actions/checkout@v3

    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: install node_modules from package.json
      run: npm install

    - name: check lint and prettier
      run: npm run check:eslint

    - name: check version vulnerabilities
      run: npm run check:vulnerabilities

    - name: test analysis-engine module
      run: npm run test

    - name: test analysis-engine log and return its coverage
      run: npm run test:log

    - name: test analysis-engine DAG and return its coverage
      run: npm run test:DAG

    - name: test analysis-engine stem and return its coverage
      run: npm run test:stem

    - name: test analysis-engine CSM and return its coverage
      run: npm run test:CSM